apiVersion: kuttl.dev/v1beta1
kind: TestStep
commands:
- script: |
    contains() { bash -ceu '[[ "$1" == *"$2"* ]]' - "$@"; }

    VERSION_OUTPUT=$(kubectl pgo version)
    { contains "${VERSION_OUTPUT}" "Client Version:"; } || {
      echo "Expected: Client Version:*"
      echo "Actual: ${VERSION_OUTPUT}"
      exit 1
    }
- script: |
    contains() { bash -ceu '[[ "$1" == *"$2"* ]]' - "$@"; }

    OPERATOR_VERSION=$(
        kubectl get crd postgresclusters.postgres-operator.crunchydata.com \
          -o go-template='{{ index .metadata.labels "app.kubernetes.io/version" }}'
    )

    VERSION_OUTPUT=$(kubectl pgo version)

    { contains "${VERSION_OUTPUT}" "Operator Version: v${OPERATOR_VERSION}"; } || {
      echo "Expected: ${OPERATOR_VERSION}"
      echo "Actual: ${VERSION_OUTPUT}"
      exit 1
    }
