# https://golangci-lint.run/usage/configuration/

linters:
  disable:
    - gofumpt
    - scopelint
  enable:
    - goheader
    - gomodguard
    - gosimple
    - importas
    - misspell
    - predeclared
    - tenv
    - tparallel
    - unconvert
  presets:
    - bugs
    - format
    - unused

linters-settings:
  gci:
    sections:
      - standard
      - default
      - prefix(github.com/crunchydata/postgres-operator-client)

  goheader:
    template: |-
      Copyright 2021 - 2022 Crunchy Data Solutions, Inc.

      Licensed under the Apache License, Version 2.0 (the "License");
      you may not use this file except in compliance with the License.
      You may obtain a copy of the License at

          http://www.apache.org/licenses/LICENSE-2.0

      Unless required by applicable law or agreed to in writing, software
      distributed under the License is distributed on an "AS IS" BASIS,
      WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
      See the License for the specific language governing permissions and
      limitations under the License.

  goimports:
    local-prefixes: github.com/crunchydata/postgres-operator-client

  gomodguard:
    blocked:
      modules:
        - gopkg.in/yaml.v2: { recommendations: [sigs.k8s.io/yaml] }
        - gopkg.in/yaml.v3: { recommendations: [sigs.k8s.io/yaml] }
        - gotest.tools: { recommendations: [gotest.tools/v3] }
        - k8s.io/kubernetes:
            reason: >
              k8s.io/kubernetes is for managing dependencies of the Kubernetes
              project, i.e. building kubelet and kubeadm.

  importas:
    no-unaliased: true
    alias:
      - pkg: k8s.io/api/(\w+)/(v[\w\w]+)
        alias: $1$2
      - pkg: k8s.io/apimachinery/pkg/apis/(\w+)/(v[\w\d]+)
        alias: $1$2
      - pkg: k8s.io/apimachinery/pkg/api/errors
        alias: apierrors

issues:
  # https://github.com/golangci/golangci-lint/issues/2239
  exclude-use-default: false
