version: "2"
linters:
  enable:
    - asasalint
    - asciicheck
    - bidichk
    - bodyclose
    - depguard
    - durationcheck
    - errchkjson
    - errorlint
    - exhaustive
    - gocheckcompilerdirectives
    - gochecksumtype
    - goheader
    - gomodguard
    - gosec
    - gosmopolitan
    - importas
    - loggercheck
    - makezero
    - misspell
    - musttag
    - nilerr
    - nilnesserr
    - noctx
    - protogetter
    - reassign
    - recvcheck
    - rowserrcheck
    - spancheck
    - sqlclosecheck
    - testifylint
    - unconvert
    - unparam
    - zerologlint
  disable:
    - contextcheck
  settings:
    depguard:
      rules:
        everything:
          deny:
            - pkg: io/ioutil
              desc: |
                Use the "io" and "os" packages instead. See https://go.dev/doc/go1.16#ioutil
        not-tests:
          files:
            - '!$test'
          deny:
            - pkg: net/http/httptest
              desc: Should be used only in tests.
            - pkg: gotest.tools
              desc: Should be used only in tests.
            - pkg: testing/*
              desc: The "testing" packages should be used only in tests.
            - pkg: github.com/crunchydata/postgres-operator-client/internal/testing/*
              desc: The "internal/testing" packages should be used only in tests.
    errchkjson:
      check-error-free-encoding: true
    exhaustive:
      default-signifies-exhaustive: true
    goheader:
      values:
        regexp:
          DATES: (202[1-4] - 2025|2025)
      template: |-
        Copyright {{ DATES }} Crunchy Data Solutions, Inc.

        SPDX-License-Identifier: Apache-2.0
    gomodguard:
      blocked:
        modules:
          - gopkg.in/yaml.v2:
              recommendations:
                - sigs.k8s.io/yaml
          - gopkg.in/yaml.v3:
              recommendations:
                - sigs.k8s.io/yaml
          - gotest.tools:
              recommendations:
                - gotest.tools/v3
          - k8s.io/kubernetes:
              reason: |
                k8s.io/kubernetes is for managing dependencies of the Kubernetes project, i.e. building kubelet and kubeadm.
    importas:
      alias:
        - pkg: k8s.io/api/(\w+)/(v[\w\w]+)
          alias: $1$2
        - pkg: k8s.io/apimachinery/pkg/apis/(\w+)/(v[\w\d]+)
          alias: $1$2
        - pkg: k8s.io/apimachinery/pkg/api/errors
          alias: apierrors
      no-unaliased: true
  exclusions:
    generated: lax
    rules:
      - linters:
          - depguard
        path: ^internal/testing
        text: gotest.tools
    paths:
      - third_party$
      - builtin$
      - examples$
formatters:
  enable:
    - gofmt
    - goimports
  settings:
    gci:
      sections:
        - standard
        - default
        - prefix(github.com/crunchydata/postgres-operator-client)
    goimports:
      local-prefixes:
        - github.com/crunchydata/postgres-operator-client
  exclusions:
    generated: lax
    paths:
      - third_party$
      - builtin$
      - examples$
