
# Setting SHELL to bash allows bash commands to be executed by recipes.
# Options are set to exit when a recipe line exits non-zero or a piped command fails.
SHELL = /usr/bin/env bash -O globstar -o pipefail
.SHELLFLAGS = -ec

GO ?= go
GO_BUILD ?= $(GO) build --trimpath
GO_TEST = $(GO) test

KUBE_CLIENT ?= kubectl
KUTTL_TEST ?= kuttl test

##@ General

# The help target prints out all targets with their descriptions organized
# beneath their categories. The categories are represented by '##@' and the
# target descriptions by '##'. The awk command is responsible for reading the
# entire set of makefiles included in this invocation, looking for lines of the
# file as 'target: ## some-help-text', and then formatting the target and help.
# Each line beginning with '##@ some-text' is formatted as a category.

.PHONY: help
help: ALIGN=18
help: ## Display this help
	@awk ' \
		BEGIN { FS = ":.*##"; printf "\nUsage:\n  make \033[36m<target>\033[0m\n" } \
		/^[a-zA-Z_0-9-]+:.*?##/ { printf "  \033[36m%-$(ALIGN)s\033[0m %s\n", $$1, $$2 } \
		/^##@/ { printf "\n\033[1m%s\033[0m\n", substr($$0, 5) } \
	' $(MAKEFILE_LIST)

##@ Development

.PHONY: all
all: check build

bin/kubectl-pgo-%: ## Build the binary
bin/kubectl-pgo-%: go.* $(shell ls -1 cmd/**/*.go internal/**/*.go)
	GOOS=$(word 1,$(subst -, ,$*)) GOARCH=$(word 2,$(subst -, ,$*)) $(GO_BUILD) -o $@ ./cmd/kubectl-pgo

.PHONY: build
build: ## Build the executable (requires Go)
build: bin/kubectl-pgo-$(subst $(eval) ,-,$(shell $(GO) env GOOS GOARCH))
	ln -fs $(notdir $<) ./bin/kubectl-pgo

.PHONY: check
check: ## Run tests
	$(GO_TEST) -cover ./...

# PGO_API_VERSION controls which PostgresCluster CRD version the kuttl tests
# target. Test YAMLs use the placeholder ${PGO_API_VERSION} for the
# postgres-operator.crunchydata.com apiVersion; the value below is substituted
# into a rendered copy of the test tree before kuttl runs. The same value is
# exported so the pgo CLI invoked from the tests picks up the same version
# via the PGO_API_VERSION env var.
PGO_API_VERSION ?= v1beta1
KUTTL_RENDERED_DIR ?= testing/kuttl/.rendered

.PHONY: render-kuttl
render-kuttl: ## Render kuttl test YAMLs with the configured PGO_API_VERSION
	@rm -rf "$(KUTTL_RENDERED_DIR)"
	@mkdir -p "$(KUTTL_RENDERED_DIR)"
	@cp -R testing/kuttl/e2e/. "$(KUTTL_RENDERED_DIR)/"
	@# Substitute only the literal $${PGO_API_VERSION} placeholder so other
	@# shell-style variables (e.g. $$NAMESPACE used in kuttl TestStep
	@# scripts) are left untouched. Each iteration fails the whole recipe
	@# on a sed/mv error -- set -e is not honored inside a while body, so
	@# we exit explicitly.
	@find "$(KUTTL_RENDERED_DIR)" -name '*.yaml' -print0 | \
	  while IFS= read -r -d '' f; do \
	    sed "s|\$${PGO_API_VERSION}|$(PGO_API_VERSION)|g" "$$f" > "$$f.tmp" || exit 1; \
	    mv "$$f.tmp" "$$f" || exit 1; \
	  done
	@echo "Rendered kuttl tests into $(KUTTL_RENDERED_DIR) with PGO_API_VERSION=$(PGO_API_VERSION)"

# Expects operator to be running
.PHONY: check-kuttl
check-kuttl: PATH := $(PWD)/bin/kubectl-pgo:$(PATH)
check-kuttl: export PGO_API_VERSION := $(PGO_API_VERSION)
check-kuttl: render-kuttl
	${KUBE_CLIENT} ${KUTTL_TEST} \
		--config testing/kuttl/kuttl-test.yaml \
		$(KUTTL_RENDERED_DIR)

.PHONY: clean
clean: ## Remove files generated by other targets
	rm -f ./bin/kubectl-pgo ./bin/kubectl-pgo-*-*
	rm -rf $(KUTTL_RENDERED_DIR)

.PHONY: cli-docs
cli-docs: ## generate cli documenation
	@echo "Generating the docs"
	rm -rf docs/content/reference && mkdir docs/content/reference
	cd docs/content/reference && $(GO) run -tags docs -exec 'env HOME=$$HOME' ../../../hack/generate-docs.go
	@echo "Configuring the _index.md file with the appropriate header"
	NL=$$'\n'; sed -e "1,/---/ { /^title:/ { \
			a \\$${NL}aliases:\\$${NL}- /reference/pgo\\$${NL}weight: 100$${NL}; \
			c \\$${NL}title: Command Reference$${NL}; \
		}; }" \
		docs/content/reference/pgo.md > \
		docs/content/reference/_index.md
	rm docs/content/reference/pgo.md
	@echo "Break out a separate code block for \`Example output\`"
	for filename in $(wildcard docs/content/reference/pgo_*.md); do \
		NL=$$'\n'; \
		sed -i "s/### Example output/\`\`\`\\$${NL}### Example output\\$${NL}\`\`\`/g" $${filename}; \
	done

.PHONY: check-cli-docs
check-cli-docs: cli-docs 
	git diff --exit-code -- docs/content/reference/

.PHONY: prep-release
prep-release:
	@echo "Replace $(OLD_VERSION) with $(NEW_VERSION)"
	sed -i "s/$${OLD_VERSION}/$${NEW_VERSION}/" internal/cmd/client_version.go docs/config.toml
	touch docs/content/releases/$(NEW_VERSION).md

.PHONY: prep-release-docs
prep-release-docs: prep-release cli-docs

.PHONY: tag
tag:
	@echo "Tagging and pushing as v$(NEW_VERSION)"
	@echo -n "Are you sure? [y/N] " && read ans && [ $${ans:-N} = y ]
	git tag "v$(NEW_VERSION)"
	git push origin "v$(NEW_VERSION)"
	git tag "d$(NEW_VERSION)"
	git push origin "d$(NEW_VERSION)"
	@echo "Make release from tag v$(NEW_VERSION)"
