# yaml-language-server: $schema=https://raw.githubusercontent.com/kyverno/chainsaw/main/.schemas/json/test-chainsaw-v1alpha1.json
apiVersion: chainsaw.kyverno.io/v1alpha1
kind: Test
metadata:
  creationTimestamp: null
  name: version
spec:
  steps:
  - name: step-00
    try:
    - script:
        content: |
          contains() { bash -ceu '[[ "$1" == *"$2"* ]]' - "$@"; }

          VERSION_OUTPUT=$(kubectl pgo version)
          { contains "${VERSION_OUTPUT}" "Client Version:"; } || {
            echo "Expected: Client Version:*"
            echo "Actual: ${VERSION_OUTPUT}"
            exit 1
          }
    - script:
        content: |
          contains() { bash -ceu '[[ "$1" == *"$2"* ]]' - "$@"; }

          OPERATOR_VERSION=$(
              kubectl get crd postgresclusters.postgres-operator.crunchydata.com \
                -o go-template='{{ index .metadata.labels "app.kubernetes.io/version" }}'
          )

          VERSION_OUTPUT=$(kubectl pgo version)

          { contains "${VERSION_OUTPUT}" "Operator Version: v${OPERATOR_VERSION}"; } || {
            echo "Expected: ${OPERATOR_VERSION}"
            echo "Actual: ${VERSION_OUTPUT}"
            exit 1
          }
  - name: step-01
    try:
    - script:
        content: |
          contains() { bash -ceu '[[ "$1" == *"$2"* ]]' - "$@"; }

          VERSION_OUTPUT=$(KUBECONFIG=blah kubectl pgo version --client)

          { contains "${VERSION_OUTPUT}" "Client Version:"; } || {
            echo "Expected: Client Version:*"
            echo "Actual: ${VERSION_OUTPUT}"
            exit 1
          }

