---
apiVersion: kuttl.dev/v1beta1
kind: TestStep
commands:
- script: echo no | kubectl-pgo --namespace $NAMESPACE create postgrescluster --pg-major-version 16 --disable-backups created-without-backups
