apiVersion: postgres-operator.crunchydata.com/v1beta1
kind: PostgresCluster
metadata:
  name: show-cluster
status:
  instances:
    - name: instance1
      readyReplicas: 1
      replicas: 1
      updatedReplicas: 1
  pgbackrest:
    repoHost:
      apiVersion: apps/v1
      kind: StatefulSet
      ready: true
    repos:
    - bound: true
      name: repo1
      replicaCreateBackupComplete: true
      stanzaCreated: true
---
apiVersion: batch/v1
kind: Job
metadata:
  labels:
    postgres-operator.crunchydata.com/cluster: show-cluster
    postgres-operator.crunchydata.com/pgbackrest-backup: replica-create
    postgres-operator.crunchydata.com/pgbackrest-repo: repo1
status:
  succeeded: 1
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  labels:
    postgres-operator.crunchydata.com/cluster: show-cluster
    postgres-operator.crunchydata.com/data: pgbackrest
    postgres-operator.crunchydata.com/pgbackrest: ""
    postgres-operator.crunchydata.com/pgbackrest-repo: repo1
    postgres-operator.crunchydata.com/pgbackrest-volume: ""
  name: show-cluster-repo1
spec:
  accessModes:
  - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi
status:
  phase: Bound
