apiVersion: kuttl.dev/v1beta1
kind: TestStep
commands:
- script: |

    PRIMARY=$(
        kubectl get pod --namespace "${NAMESPACE}" \
          --output name --selector '
            postgres-operator.crunchydata.com/cluster=show-cluster,
            postgres-operator.crunchydata.com/role=master'
    )

    CLI_HA=$(
        kubectl-pgo --namespace "${NAMESPACE}" show backup show-cluster -o bad 2>&1
    )

    status=$?
    if [ "$status" -ne 1 ]; then
        echo "expected bad format to fail"
        exit 1
    fi

    # check command output is not empty and contains the expected error
    # Note: case is used as it allows for the use of a wildcard (*)
    # and is POSIX compliant
    case "$CLI_HA" in
    "")
        exit 1
        ;;
    *"must be one of \"text\", \"json\""*)
        exit 0
        ;;
    esac

    exit 1
