---
apiVersion: kuttl.dev/v1beta1
kind: TestStep
commands:
- script: kubectl-pgo --namespace $NAMESPACE support export kuttl-support-monitoring-cluster -o .
- script: tar -xf ./crunchy_k8s_support_export_*.tar
- script: |
    #!/bin/bash

    CLEANUP="rm -r ./kuttl-support-monitoring-cluster ./monitoring ./crunchy_k8s_support_export_*.tar"
    CLUSTER_DIR="./kuttl-support-monitoring-cluster/logs/"
    MONITORING_DIR="./monitoring/logs/"

    # check for exporter, prometheus, grafana and alertmanager logs
    found=$(find ${CLUSTER_DIR} -name "exporter" | wc -l)
    if [ "${found}" -eq 0 ]; then
      echo "exporter not found"
      eval "$CLEANUP"
      exit 1
    fi

    found=$(find ${MONITORING_DIR} -name "prometheus" | wc -l)
    if [ "${found}" -eq 0 ]; then
      echo "prometheus not found"
      eval "$CLEANUP"
      exit 1
    fi

    found=$(find ${MONITORING_DIR} -name "grafana" | wc -l)
    if [ "${found}" -eq 0 ]; then
      echo "grafana not found"
      eval "$CLEANUP"
      exit 1
    fi

    found=$(find ${MONITORING_DIR} -name "alertmanager" | wc -l)
    if [ "${found}" -eq 0 ]; then
      echo "alertmanager not found"
      eval "$CLEANUP"
      exit 1
    fi

- script: rm -r ./kuttl-support-monitoring-cluster ./monitoring ./crunchy_k8s_support_export_*.tar
