apiVersion: postgres-operator.crunchydata.com/v1beta1
kind: PostgresCluster
metadata:
  name: kuttl-support-cluster
---
apiVersion: v1
kind: LimitRange
metadata:
  name: kuttl-test-limitrange
---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: kuttl-test-ingress
