---
apiVersion: postgres-operator.crunchydata.com/v1beta1
kind: PostgresCluster
metadata:
  name: kuttl-support-cluster
---
apiVersion: postgres-operator.crunchydata.com/v1beta1
kind: PostgresCluster
metadata:  
  name: kuttl-support-monitoring-cluster
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: crunchy-prometheus
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: crunchy-grafana
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: crunchy-alertmanager
