apiVersion: postgres-operator.crunchydata.com/v1beta1
kind: PostgresCluster
metadata:
  name: kuttl-support-cluster-other
spec:
  backups:
    pgbackrest:
      repos:
        - name: repo1
          volume:
            volumeClaimSpec:
              accessModes:
                - "ReadWriteOnce"
              resources:
                requests:
                  storage: 1Gi
  instances:
    - dataVolumeClaimSpec:
        accessModes:
        - "ReadWriteOnce"
        resources:
          requests:
            storage: 1Gi
      replicas: 1
  postgresVersion: 14
status:
  instances:
    - name: "00"
      readyReplicas: 1
      replicas: 1
      updatedReplicas: 1
---
apiVersion: v1
kind: LimitRange
metadata:
  name: storagelimits
---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: minimal-test-ingress
