apiVersion: kuttl.dev/v1beta1
kind: TestStep
commands:
- script: |
    echo yes | kubectl-pgo --namespace $NAMESPACE delete postgrescluster fake

    status=$?
    if [ $status -eq 1 ]; then
        echo "pgo command returned 1 as expected"
        exit 0
    fi
