apiVersion: kuttl.dev/v1beta1
kind: TestStep
commands:
- script: |
    RESULT=$(kubectl-pgo --namespace "${NAMESPACE}" backup backup-cluster --repoName repo1 --options="--type=full" 2>&1)
    STATUS=$?

    echo "RESULT from taking backup: ${RESULT}"

    if [ "${STATUS-0}" -eq 0 ]; then
      printf 'Expected error, got none\n'
      exit 1
    fi

    # get lowercase for result
    lower=$(echo "$RESULT" | tr '[:upper:]' '[:lower:]')

    # check for the substring using POSIX compliant parameter-expansion.
    # If the variable contains the substring after the '%', it does not return
    # the entire string content, leading to a mismatch. If both substrings are found,
    # the test passes.
    # - https://www.gnu.org/software/bash/manual/html_node/Shell-Parameter-Expansion.html
    if [ "${lower}" != "${lower%"conflict"*}" ] && [ "${RESULT}" != "${RESULT%"repoName"*}" ]; then
      exit 0
    fi

    printf 'Expected conflict on repoName, got %s\n' "${RESULT}"
    exit 1
