---
# The cluster should not have changed.
apiVersion: postgres-operator.crunchydata.com/${PGO_API_VERSION}
kind: PostgresCluster
metadata:
  name: backup-cluster
spec:
  backups:
    pgbackrest:
      manual:
        repoName: repo3
