---
# The cluster should not have changed.
apiVersion: postgres-operator.crunchydata.com/v1beta1
kind: PostgresCluster
metadata:
  name: backup-cluster
spec:
  backups:
    pgbackrest:
      manual:
        repoName: repo3
