apiVersion: chainsaw.kyverno.io/v1alpha1
kind: StepTemplate
metadata:
  name: create-cluster-from-manifest
spec:
  try:
    -
      description: >
        Create a standard cluster with two replicas and a single pgBackRest repository
      apply:
        resource:
          apiVersion: postgres-operator.crunchydata.com/v1beta1
          kind: PostgresCluster
          metadata:
            name: ($cluster)
          spec:
            postgresVersion: (to_number($postgresVersion))
            instances:
              - replicas: 2
                dataVolumeClaimSpec: { accessModes: [ "ReadWriteOnce" ], resources: { requests: { storage: 1Gi } } }
            backups:
              pgbackrest:
                global:
                  log-level-console: detail
                  log-level-file: detail
                  start-fast: 'y'
                repos:
                  - name: repo1
                    volume:
                      volumeClaimSpec: { accessModes: ["ReadWriteOnce"], resources: { requests: { storage: 1Gi } } }

  catch:
    - describe:
        apiVersion: v1
        kind: Pod
        selector: (concat('postgres-operator.crunchydata.com/cluster=', $cluster))
