apiVersion: chainsaw.kyverno.io/v1alpha1
kind: StepTemplate
metadata:
  name: replica-backup-complete
spec:
  try:
    - sleep:
        duration: 30s

    - description: Wait for initial backup to complete'
      wait:
        for:
          jsonPath:
            path: '{.status.succeeded}'
            value: "1"
        timeout: 5m
        apiVersion: batch/v1
        kind: Job
        namespace: ($namespace)
        selector: postgres-operator.crunchydata.com/pgbackrest-backup=replica-create
  catch:
    - describe:
        apiVersion: v1
        kind: Pod
        selector: (concat('postgres-operator.crunchydata.com/cluster=', $cluster))
