apiVersion: kuttl.dev/v1beta1
kind: TestStep
commands:
- script: |
    # Run a restore without required arguments.
    # The PostgresCluster has no restore section populated, so the "--repoName" flag is required.

    RESULT=$( 2>&1 kubectl-pgo --namespace "${NAMESPACE}" restore restore-cluster )
    STATUS=$?

    [[ "${STATUS}" -ne 0 ]] || {
      echo "Expected failure, got ${STATUS}"
      echo "STDOUT+STDERR: ${RESULT}"
      exit 1
    }

    [[ "${RESULT}" == 'Error:'*'repoName: Required value' ]] || {
      echo "Expected an error message, got:"
      echo "${RESULT}"
      exit 1
    }

    RESTORE=$(
      kubectl --namespace "${NAMESPACE}" get postgrescluster/restore-cluster \
        --output 'jsonpath-as-json={.spec.backups.pgbackrest.restore}'
    )

    [[ "${RESTORE}" == '[]' ]] || {
      echo "Expected restore section to be empty, got ${RESTORE}"
      exit 1
    }
