---
apiVersion: postgres-operator.crunchydata.com/v1beta1
kind: PostgresCluster
metadata:
  name: restore-cluster

  # There is a restore annotation asserted in the TestStep.

spec:
  backups:
    pgbackrest:
      # The restore section should be populated.
      restore:
        enabled: true
        repoName: repo1

status:
  pgbackrest:
    # The restore should succeed.
    restore:
      succeeded: 1

  # Wait for the instance to come back, also.
  instances:
    - replicas: 1
      readyReplicas: 1
