apiVersion: kuttl.dev/v1beta1
kind: TestStep
commands:
- script: |
    # Allow for the restore repository to be predefined elsewhere.

    # kubectl takes ownership, usually as "kubectl-patch".
    kubectl --namespace "${NAMESPACE}" patch postgrescluster/restore-cluster \
      --type 'merge' --patch '{
        "spec": {
          "backups": {
            "pgbackrest": {
              "restore": { "enabled": true, "repoName": "repo1" }
            }
          }
        }
      }' || exit

    BEFORE=$(
      kubectl --namespace "${NAMESPACE}" get postgrescluster/restore-cluster \
        --output "jsonpath-as-json={.metadata.managedFields}"
    ) || exit

    RESULT=$(echo yes |
      kubectl-pgo --namespace "${NAMESPACE}" restore restore-cluster \
        --options "--buffer-size=8MiB"
    )
    STATUS=$?

    [[ "${STATUS}" -eq 0 ]] || {
      echo "Expected success, got ${STATUS}"
      echo "STDOUT: ${RESULT}"
      echo "Managed Fields: ${BEFORE}"
      exit 1
    }

    [[ "${RESULT}" == *'patched'* ]] || {
      echo "Expected to patch, got:"
      echo "${RESULT}"
      exit 1
    }

    RESTORE=$(
      kubectl --namespace "${NAMESPACE}" get postgrescluster/restore-cluster \
        --output "jsonpath-as-json={.metadata.annotations['postgres-operator\.crunchydata\.com/pgbackrest-restore']}"
    )

    # Wait for the restore process to be reflected in status.
    for _ in {1..15}; do
      STATUS=$(
        kubectl --namespace "${NAMESPACE}" get postgrescluster/restore-cluster \
          --output "jsonpath-as-json={.status.pgbackrest.restore.id}"
      )

      [[ "${STATUS}" == "${RESTORE}" ]] && break

      sleep 1
    done

    [[ "${STATUS}" == "${RESTORE}" ]] || {
      echo "Expected restore request to be processed, got ${STATUS} != ${RESTORE}"
      exit 1
    }
