name: Linters

on:
  pull_request:
    branches:
      - main

jobs:
  golangci-lint:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      checks: write
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-go@v5
        with: { go-version: stable }

      - uses: golangci/golangci-lint-action@v7
        with:
          version: latest
          args: --timeout=5m
