name: Tests

on:
  pull_request:
    branches:
      - main
  push:
    branches:
      - main

jobs:
  go-test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-go@v3
        with: { go-version: 1.x }

      - run: make check
      - run: make check-cli-docs

  kuttl-test:
    runs-on: ubuntu-latest
    needs: [go-test]
    strategy:
      fail-fast: false
      matrix:
        kubernetes: [v1.27, v1.24, v1.21]
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-go@v3
        with: { go-version: 1.x }

      - name: Start k3s
        uses: ./.github/actions/k3d
        with:
          k3s-channel: "${{ matrix.kubernetes }}"

      - name: Build CLI
        run: make build

      - name: Create operator namespace
        run: kubectl create namespace postgres-operator

      - name: Install Operator
        run: helm install pgo oci://registry.developers.crunchydata.com/crunchydata/pgo -n postgres-operator

      - name: Use bash, so we can use double square-bracket [[ syntax in our scripts
        run: |
          sudo ln -s bash /bin/sh.bash
          sudo mv /bin/sh.bash /bin/sh

      - name: Install kuttl
        run: |
          curl -Lo /usr/local/bin/kubectl-kuttl https://github.com/kudobuilder/kuttl/releases/download/v0.15.0/kubectl-kuttl_0.15.0_linux_x86_64
          chmod +x /usr/local/bin/kubectl-kuttl

      - name: Run kuttl
        run: |
          make check-kuttl
